name: Ian Howell
favicon: null
layout_spectrum: 0.7570248066913337
typography_spectrum: 0.1648338562808931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0663376864977181
  lightness: 0.09325609588995576
  saturation: 0.9110598496627063
  rhythmicContrast: 0.7617640078533441
purpose: []
